server:
  address: ":8085"

stores:
  test:
    type: consul
    config:
      prefix: bundles/test
      consul:
        address: http://consul1:8500

webhooks:
  test:
    type: gogs
    config:
      secret: sauce
      events:
        - push

subscribers:
  test:
    type: consul
    config:
      prefix: bundles/test
      consul:
        address: http://consul1:8500


bundles:
  test:
    store: test
    webhook: test
    subscriber: test
    